name: build-project
run-name: Build is triggered by ${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: ( mkdir ./build; cd ./build && cmake -DVERSION=12 ../ && cmake --build . && cmake --build . --target package )
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: |
